// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package user

import (
	"database/sql"
	"time"
)

type User struct {
	ID        uint32
	FirstName string
	LastName  string
	BirthDate time.Time
	Email     string
	Username  string
	Password  string
	CreatedAt sql.NullTime
}
