// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package category

import (
	"database/sql"
)

type Category struct {
	ID          uint32
	Name        string
	Description string
	ParentID    sql.NullInt32
	CreatedAt   sql.NullTime
}
